cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
   path('', views.cart_detail_view, name='cart_detail'),
   path('<int:product_id>/add/', views.add_to_cart_view, name='cart_add'),
   path('<int:product_id>/remove/', views.remove_from_cart_view, name='cart_remove'),
   path('clear/', views.clear_cart_view, name='cart_clear'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payment/', include('payment.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms


class AddToCartProductForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 30)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST, require_GET
from django.contrib import messages
from django.utils.translation import gettext as _

from .cart import Cart
from .forms import AddToCartProductForm
from products.models import Product


def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_quantity_form'] = AddToCartProductForm(initial={
            'quantity': item['quantity'],
            'inplace': True
        })

    return render(request, 'cart/cart.html', {'cart': cart})


@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    quantity_form = AddToCartProductForm(request.POST)

    if quantity_form.is_valid():
        cleaned_data = quantity_form.cleaned_data
        quantity = cleaned_data['quantity']
        replace_current_quantity = cleaned_data['inplace']
        cart.add(product, quantity, replace_current_quantity)
        messages.success(request, _('Product successfully added to cart.'))

        return redirect('cart:cart_detail')


def remove_from_cart_view(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    cart.remove(product)
    messages.error(request, _('Product successfully removed from cart.'))

    return redirect('cart:cart_detail')


def clear_cart_view(request):
    cart = Cart(request)
    cart.clear()
    messages.warning(request, _('Cart was cleared.'))

    return redirect('product_list')

cart/templates/cart/Breadcrumb.html
{% load i18n %}

{% load  static %}

<!-- Breadcrumb area Start -->
<div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                    <h1 class="page-title">{{ breadcrumb }}</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb area End -->

cart/templates/cart/cart.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% load i18n %}

{% load persian_number %}

{% load humanize %}

{% block page_title %}{% trans 'cart page' %}{% endblock page_title %}

{% block content %}

    {% trans 'cart' as x %}
    {% include 'cart/Breadcrumb.html' with breadcrumb=x %}

    <!-- Main Content Wrapper Start -->
    <div class="main-content-wrapper">
        <div class="page-content-inner ptb--80">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-md--50">
                        <div class="row no-gutters">
                            <div class="col-12">
                                {% if cart %}
                                    <div class="table-content table-responsive">
                                        <table class="table text-center">
                                            <thead>
                                            <tr>
                                                <th>&nbsp;</th>
                                                <th>عکس محصول</th>
                                                <th> نام محصول</th>
                                                <th>قیمت</th>
                                                <th>مقدار</th>
                                                <th>مجموع</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in cart %}
                                                <tr>
                                                    <td class="product-remove text-left"><a
                                                            href="{% url 'cart:cart_remove' item.product_obj.id %}"><i
                                                            class="flaticon flaticon-cross"></i></a></td>
                                                    <td class="product-thumbnail text-left">
                                                        <img src="{{ item.product_obj.image.url }}"
                                                             alt="Product Thumnail">
                                                    </td>
                                                    <td class="product-name">
                                                        <h3>
                                                            <a href="{{ item.product_obj.get_absolute_url }}">{{ item.product_obj.title }}</a>
                                                        </h3>
                                                    </td>
                                                    <td class="product-price">
                                                            <span class="product-price-wrapper"><span
                                                                    class="money">{{ item.product_obj.price|intcomma:False|translate_number  }} {% trans '$' %}</span>
                                                            </span>
                                                    </td>
                                                    <td class="product-quantity">
                                                        <form class="d-flex"
                                                              action="{% url 'cart:cart_add' item.product_obj.id %}"
                                                              method="post">
                                                            {% csrf_token %}
                                                            <div class="quantity">
                                                                <input type="number" class="quantity-input"
                                                                       name="quantity"
                                                                       id="qty-1" value="{{ item.quantity }}" min="1">
                                                            </div>
                                                            {{ item.product_update_quantity_form.inplace }}
                                                            <button type="submit"><i class="fa fa-refresh"></i></button>
                                                        </form>
                                                    </td>
                                                    <td class="product-total-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.total_price|intcomma:False|translate_number  }} {% trans '$' %}</span>
                                                            </span>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                {% else %}
                                    <a href="{% url 'product_list' %}">{% trans 'please add some product to your cart' %}</a>
                                {% endif %}
                            </div>
                        </div>
                        {% if cart %}
                            <div class="row no-gutters border-top pt--20 mt--20">
                                <div class="col-sm-6 text-sm-right">
                                    <a href="{% url 'cart:cart_clear' %}"
                                       class="cart-form__btn">{% trans 'clear the cart' %}</a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-collaterals">
                            <div class="cart-totals">
                                <h5 class="font-size-14 font-bold mb--15">{% trans 'total' %}</h5>
                                <div class="cart-calculator">
                                    <div class="cart-calculator__item order-total">
                                        <div class="cart-calculator__item--head">
                                            <span>{% trans 'total price' %}</span>
                                        </div>
                                        <div class="cart-calculator__item--value">
                                                <span class="product-price-wrapper">
                                                    <span class="money">{{ cart.get_total_price|intcomma:False|translate_number  }} {% trans '$' %}</span>
                                                </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'order_create' %}" class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                {% trans 'order' %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Wrapper Start -->

{% endblock content %}

cart/templates/cart/cart_side.html
{% load i18n %}

{% load  static %}

{% load persian_number %}

{% load humanize %}

<!-- Mini Cart Start -->
<aside class="mini-cart" id="miniCart">
    <div class="mini-cart-wrapper">
        <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
        <div class="mini-cart-inner">
            <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">سبد خرید</h3>
            <div class="mini-cart__content">
                <ul class="mini-cart__list text-right">
                    {% for item in cart %}
                        <li class="mini-cart__product d-flex justify-content-between">
                            <div class="mini-cart__product__image">
                                <a href="{{ item.product_obj.get_absolute_url }}">
                                    <img src="{{ item.product_obj.image.url }}" alt="products">
                                </a>
                            </div>
                            <div class="mini-cart__product__content pt-2">
                                    <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                        <a href="{{ item.product_obj.get_absolute_url }}">{{ item.product_obj.title }}</a>
                                        <a href="{% url 'cart:cart_remove' item.product_obj.id %}" class="">
                                            &#10060;
                                        </a>
                                    </span>
                                <span class="mini-cart__product__quantity">
                                        <span>{{ item.product_obj.price|intcomma:False|translate_number }} {% trans '$' %}</span> &#215; <span>{{ item.quantity }}</span>
                                    </span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                {% if cart %}
                    <div class="mini-cart__total">
                        <span>{% trans 'total price' %}</span>
                        <span class="ammount">{{ cart.get_total_price|intcomma:False|translate_number }} {% trans '$' %}</span>
                    </div>
                    <div class="mini-cart__buttons">
                        <a href="{% url 'cart:cart_detail' %}"
                           class="btn btn-fullwidth btn-bg-sand mb--20">{% trans 'go to cart' %}</a>
                        <a href="{% url 'order_create' %}" class="btn btn-fullwidth btn-bg-sand">{% trans 'checkout' %}</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</aside>
<!-- Mini Cart End -->